# Generated by Django 4.2.3 on 2023-07-24 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, unique=True)),
                ('title_ru', models.CharField(db_index=True, max_length=100, null=True, unique=True)),
                ('title_en', models.CharField(db_index=True, max_length=100, null=True, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('template', models.FileField(upload_to='articles')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name_ru', models.CharField(db_index=True, max_length=50, null=True, unique=True)),
                ('name_en', models.CharField(db_index=True, max_length=50, null=True, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('articles', models.ManyToManyField(blank=True, to='Base.article')),
                ('subcategories', models.ManyToManyField(blank=True, to='Base.category')),
            ],
        ),
    ]
