# Generated by Django 4.1 on 2023-08-21 05:33

import Base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, unique=True)),
                ('title_ru', models.CharField(db_index=True, max_length=100, null=True, unique=True)),
                ('title_en', models.CharField(db_index=True, max_length=100, null=True, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('template', models.FileField(upload_to=Base.models.user_directory_path)),
                ('time_added', models.DateTimeField(auto_now_add=True)),
                ('time_updated', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True)),
                ('img1', models.ImageField(blank=True, upload_to=Base.models.user_directory_path)),
                ('img2', models.ImageField(blank=True, upload_to=Base.models.user_directory_path)),
                ('img3', models.ImageField(blank=True, upload_to=Base.models.user_directory_path)),
                ('img4', models.ImageField(blank=True, upload_to=Base.models.user_directory_path)),
                ('img5', models.ImageField(blank=True, upload_to=Base.models.user_directory_path)),
                ('img6', models.ImageField(blank=True, upload_to=Base.models.user_directory_path)),
                ('img7', models.ImageField(blank=True, upload_to=Base.models.user_directory_path)),
                ('img8', models.ImageField(blank=True, upload_to=Base.models.user_directory_path)),
                ('img9', models.ImageField(blank=True, upload_to=Base.models.user_directory_path)),
                ('img10', models.ImageField(blank=True, upload_to=Base.models.user_directory_path)),
                ('img11', models.ImageField(blank=True, upload_to=Base.models.user_directory_path)),
                ('img12', models.ImageField(blank=True, upload_to=Base.models.user_directory_path)),
                ('img13', models.ImageField(blank=True, upload_to=Base.models.user_directory_path)),
                ('img14', models.ImageField(blank=True, upload_to=Base.models.user_directory_path)),
                ('img15', models.ImageField(blank=True, upload_to=Base.models.user_directory_path)),
                ('img16', models.ImageField(blank=True, upload_to=Base.models.user_directory_path)),
                ('img17', models.ImageField(blank=True, upload_to=Base.models.user_directory_path)),
                ('img18', models.ImageField(blank=True, upload_to=Base.models.user_directory_path)),
                ('img19', models.ImageField(blank=True, upload_to=Base.models.user_directory_path)),
                ('img20', models.ImageField(blank=True, upload_to=Base.models.user_directory_path)),
                ('img21', models.ImageField(blank=True, upload_to=Base.models.user_directory_path)),
                ('img22', models.ImageField(blank=True, upload_to=Base.models.user_directory_path)),
                ('img23', models.ImageField(blank=True, upload_to=Base.models.user_directory_path)),
                ('img24', models.ImageField(blank=True, upload_to=Base.models.user_directory_path)),
                ('img25', models.ImageField(blank=True, upload_to=Base.models.user_directory_path)),
                ('img26', models.ImageField(blank=True, upload_to=Base.models.user_directory_path)),
                ('img27', models.ImageField(blank=True, upload_to=Base.models.user_directory_path)),
                ('img28', models.ImageField(blank=True, upload_to=Base.models.user_directory_path)),
                ('img29', models.ImageField(blank=True, upload_to=Base.models.user_directory_path)),
                ('img30', models.ImageField(blank=True, upload_to=Base.models.user_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name_ru', models.CharField(db_index=True, max_length=50, null=True, unique=True)),
                ('name_en', models.CharField(db_index=True, max_length=50, null=True, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('articles', models.ManyToManyField(blank=True, to='Base.article')),
                ('subcategories', models.ManyToManyField(blank=True, to='Base.category')),
            ],
        ),
    ]
