# Generated by Django 4.2.3 on 2023-07-25 10:17

import Base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='img1',
            field=models.ImageField(blank=True, upload_to=Base.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='article',
            name='img10',
            field=models.ImageField(blank=True, upload_to=Base.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='article',
            name='img11',
            field=models.ImageField(blank=True, upload_to=Base.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='article',
            name='img12',
            field=models.ImageField(blank=True, upload_to=Base.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='article',
            name='img13',
            field=models.ImageField(blank=True, upload_to=Base.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='article',
            name='img14',
            field=models.ImageField(blank=True, upload_to=Base.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='article',
            name='img15',
            field=models.ImageField(blank=True, upload_to=Base.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='article',
            name='img16',
            field=models.ImageField(blank=True, upload_to=Base.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='article',
            name='img17',
            field=models.ImageField(blank=True, upload_to=Base.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='article',
            name='img18',
            field=models.ImageField(blank=True, upload_to=Base.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='article',
            name='img19',
            field=models.ImageField(blank=True, upload_to=Base.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='article',
            name='img2',
            field=models.ImageField(blank=True, upload_to=Base.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='article',
            name='img20',
            field=models.ImageField(blank=True, upload_to=Base.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='article',
            name='img21',
            field=models.ImageField(blank=True, upload_to=Base.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='article',
            name='img22',
            field=models.ImageField(blank=True, upload_to=Base.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='article',
            name='img23',
            field=models.ImageField(blank=True, upload_to=Base.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='article',
            name='img24',
            field=models.ImageField(blank=True, upload_to=Base.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='article',
            name='img25',
            field=models.ImageField(blank=True, upload_to=Base.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='article',
            name='img26',
            field=models.ImageField(blank=True, upload_to=Base.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='article',
            name='img27',
            field=models.ImageField(blank=True, upload_to=Base.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='article',
            name='img28',
            field=models.ImageField(blank=True, upload_to=Base.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='article',
            name='img29',
            field=models.ImageField(blank=True, upload_to=Base.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='article',
            name='img3',
            field=models.ImageField(blank=True, upload_to=Base.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='article',
            name='img30',
            field=models.ImageField(blank=True, upload_to=Base.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='article',
            name='img4',
            field=models.ImageField(blank=True, upload_to=Base.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='article',
            name='img5',
            field=models.ImageField(blank=True, upload_to=Base.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='article',
            name='img6',
            field=models.ImageField(blank=True, upload_to=Base.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='article',
            name='img7',
            field=models.ImageField(blank=True, upload_to=Base.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='article',
            name='img8',
            field=models.ImageField(blank=True, upload_to=Base.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='article',
            name='img9',
            field=models.ImageField(blank=True, upload_to=Base.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='article',
            name='template',
            field=models.FileField(upload_to=Base.models.user_directory_path),
        ),
    ]
