# Generated by Django 4.1 on 2023-09-03 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0002_article_likes_article_shares'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20)),
                ('position', models.CharField(db_index=True, max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(db_index=True, max_length=500)),
            ],
        ),
    ]
