# Generated by Django 4.1 on 2023-09-06 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0005_article_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='rank',
            field=models.FloatField(default=0.0),
        ),
    ]
