# Generated by Django 4.1 on 2023-09-07 07:38

import Base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0006_article_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='template_shorter',
            field=models.FileField(blank=True, upload_to=Base.models.user_directory_path),
        ),
    ]
