# Generated by Django 4.1 on 2023-09-08 08:23

import Base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0007_article_template_shorter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='template_shorter',
            field=models.FileField(blank=True, null=True, upload_to=Base.models.user_directory_path),
        ),
    ]
